name: CI/CD Wayshub-Frontend Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add app-server to known hosts
        run: ssh-keyscan -H 10.194.61.3 >> ~/.ssh/known_hosts

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t ramdhanifauzi/wayshub-frontend:staging .

      - name: Push image to DockerHub
        run: docker push ramdhanifauzi/wayshub-frontend:staging

      - name: Create .env on app-server
        run: |
          ssh fauzi@10.194.61.3 "echo 'REACT_APP_BASEURL=${{ secrets.REACT_APP_BASEURL }}' > ~/fe-staging/.env"

      - name: Deploy to app-server
        run: |
          ssh fauzi@10.194.61.3 "cd ~/fe-staging && docker compose pull && docker compose up -d"
